spring:
  datasource:
    url: jdbc:mysql://localhost:3306/king-admin?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: zzl81cn
# admin @dmin
server:
  port: 9001

logging:
  config: classpath:logback-spring.xml
  level: debug
